//
// Copyright (c) 2022 ZettaScale Technology
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
//
// Contributors:
//   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
//

use async_std::sync::Mutex;
use async_trait::async_trait;
use opencv::{core, imgproc, objdetect, prelude::*, types};
use std::sync::Arc;
use zenoh_flow::{bail, prelude::*};

#[derive(Debug)]
struct FaceDetection;

static INPUT: &str = "Frame";
static OUTPUT: &str = "Frame";

struct FDState {
    pub face: objdetect::CascadeClassifier,
    pub encode_options: opencv::types::VectorOfi32,
}

// because of opencv
impl std::fmt::Debug for FDState {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "FDState:...",)
    }
}

impl FDState {
    fn new(configuration: &Option<Configuration>) -> Self {
        let default_neural_network = &"haarcascades/haarcascade_frontalface_alt.xml".to_owned();
        let neural_network = if let Some(configuration) = configuration {
            configuration["neural-network"]
                .as_str()
                .unwrap_or(default_neural_network)
        } else {
            default_neural_network
        };

        let xml = core::find_file(neural_network, true, false).unwrap();
        let face = objdetect::CascadeClassifier::new(&xml).unwrap();
        let encode_options = opencv::types::VectorOfi32::new();

        Self {
            face,
            encode_options,
        }
    }

    pub fn infer(&mut self, frame: Vec<u8>) -> Vec<u8> {
        // Decode Image
        let mut frame = opencv::imgcodecs::imdecode(
            &opencv::types::VectorOfu8::from_iter(frame),
            opencv::imgcodecs::IMREAD_COLOR,
        )
        .unwrap();

        let mut gray = Mat::default();
        imgproc::cvt_color(&frame, &mut gray, imgproc::COLOR_BGR2GRAY, 0).unwrap();
        let mut reduced = Mat::default();
        imgproc::resize(
            &gray,
            &mut reduced,
            core::Size {
                width: 0,
                height: 0,
            },
            0.25f64,
            0.25f64,
            imgproc::INTER_LINEAR,
        )
        .unwrap();
        let mut faces = types::VectorOfRect::new();
        self.face
            .detect_multi_scale(
                &reduced,
                &mut faces,
                1.1,
                2,
                objdetect::CASCADE_SCALE_IMAGE,
                core::Size {
                    width: 30,
                    height: 30,
                },
                core::Size {
                    width: 0,
                    height: 0,
                },
            )
            .unwrap();
        for face in faces {
            let scaled_face = core::Rect {
                x: face.x * 4,
                y: face.y * 4,
                width: face.width * 4,
                height: face.height * 4,
            };
            imgproc::rectangle(
                &mut frame,
                scaled_face,
                core::Scalar::new(0f64, 255f64, -1f64, -1f64),
                10,
                1,
                0,
            )
            .unwrap();
        }

        let mut buf = opencv::types::VectorOfu8::new();
        opencv::imgcodecs::imencode(".jpg", &frame, &mut buf, &self.encode_options).unwrap();
        buf.into()
    }
}

#[async_trait]
impl Operator for FaceDetection {
    async fn setup(
        &self,
        _context: &mut Context,
        configuration: &Option<Configuration>,
        mut inputs: Inputs,
        mut outputs: Outputs,
    ) -> Result<Option<Box<dyn AsyncIteration>>> {
        let state = Arc::new(Mutex::new(FDState::new(configuration)));

        let input_frame = inputs.take_into_arc(INPUT).unwrap();
        let output_frame = outputs.take_into_arc(OUTPUT).unwrap();

        Ok(Some(Box::new(move || {
            let state = state.clone();
            let input_frame = input_frame.clone();
            let output_frame = output_frame.clone();

            async move {
                let raw_input = input_frame.recv_async().await?;
                if let Message::Data(mut msg) = raw_input {
                    let data = msg.get_inner_data().try_as_bytes()?.as_ref().clone();

                    let buffer: Vec<u8>;
                    {
                        buffer = state.lock().await.infer(data);
                    }

                    output_frame.send_async(Data::from(buffer), None).await
                } else {
                    bail!(ErrorKind::InvalidData, "No data")
                }
            }
        })))
    }
}

// Also generated by macro
zenoh_flow::export_operator!(register);

fn register() -> Result<Arc<dyn Operator>> {
    Ok(Arc::new(FaceDetection) as Arc<dyn Operator>)
}
