//
// Copyright (c) 2022 ZettaScale Technology
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
//
// Contributors:
//   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
//
//#![feature(async_closure)]

use async_trait::async_trait;
use std::sync::Arc;
use zenoh_flow::prelude::*;
use zenoh_flow_example_types::ZFUsize;

#[derive(Debug)]
struct SumAndSend;

#[derive(Debug, Clone)]
struct SumAndSendState {
    pub x: ZFUsize,
}

static INPUT: &str = "Number";
static OUTPUT: &str = "Sum";
#[async_trait]
impl Operator for SumAndSend {
    async fn setup(
        &self,
        _context: &mut Context,
        _configuration: &Option<Configuration>,
        mut inputs: Inputs,
        mut outputs: Outputs,
    ) -> Result<Option<Arc<dyn AsyncIteration>>> {
        let mut state = SumAndSendState { x: ZFUsize(0) };

        let input_value = inputs.take(INPUT).unwrap();
        let output_value = outputs.take(OUTPUT).unwrap();

        Ok(Some(Arc::new(move || async move {
            let data = match input_value.recv_async().await.unwrap() {
                Message::Data(mut msg) => Ok(msg.get_inner_data().try_get::<ZFUsize>()?.clone()),
                _ => Err(zferror!(ErrorKind::Empty, "No data")),
            }?;

            let res = ZFUsize(state.x.0 + data.0);
            state.x = res.clone();

            output_value.send_async(Data::from(res), None).await
        })))
    }
}

// Also generated by macro
zenoh_flow::export_operator!(register);

fn register() -> Result<Arc<dyn Operator>> {
    Ok(Arc::new(SumAndSend) as Arc<dyn Operator>)
}
