# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\")\n\x05MyMsg\x12\x0f\n\x07u_value\x18\x01 \x01(\x04\x12\x0f\n\x07s_value\x18\x02 \x01(\tb\x06proto3')



_MYMSG = DESCRIPTOR.message_types_by_name['MyMsg']
MyMsg = _reflection.GeneratedProtocolMessageType('MyMsg', (_message.Message,), {
  'DESCRIPTOR' : _MYMSG,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:MyMsg)
  })
_sym_db.RegisterMessage(MyMsg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MYMSG._serialized_start=17
  _MYMSG._serialized_end=58
# @@protoc_insertion_point(module_scope)
