#
# Copyright (c) 2017, 2022 ZettaScale Technology.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale zenoh team, <zenoh@zettascale.tech>
#

name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  schedule:
    - cron: '0 6 * * 1-5'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt, clippy

      - name: Code format check [getting started]
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check --manifest-path ./getting-started/nodes/rust/Cargo.toml --all

      - name: Code format check [period miss detector]
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check --manifest-path ./period-miss-detector/nodes/rust/Cargo.toml --all

      - name: Code format check [montblanc]
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check --manifest-path ./montblanc/Cargo.toml --all

      - name: Clippy [getting-started]
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path ./getting-started/nodes/rust/Cargo.toml --all -- -D warnings

      - name: Clippy [period-miss-detector]
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path ./period-miss-detector/nodes/rust/Cargo.toml --all -- -D warnings

      - name: Clippy [montblanc]
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path ./montblanc/Cargo.toml --all -- -D warnings

      - name: Build [getting-started]
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path ./getting-started/nodes/rust/Cargo.toml --verbose --all-targets

      - name: Build [period-miss-detector]
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path ./period-miss-detector/nodes/rust/Cargo.toml --verbose --all-targets

      - name: Build [montblanc]
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path ./montblanc/Cargo.toml --verbose --all-targets